# Generated by Django 4.0.3 on 2026-09-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradecore_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='geolocation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
