# Generated by Django 4.1.4 on 2026-09-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_messagecategories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-created_on'], name='log_created_on_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', '-created_on'], name='log_user_created_idx'),
        ),
    ]
